# Welcome to Serverless!
service: hasmutationdna
app: hasmutationdna-api

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  load:
    handler: controllers/product.handler
    events:
        - http:
            path: /
            method: get
        - http:
            path: /mutation
            method: post
        - http:
            path: /stats
            method: get
